import type { AggregateDashboard, IssueDetail, ProjectDetail, SelfDefectRouteSummary } from "@/src/types";

const baseCapacity = { max_sessions: 4, running_sessions: 2, available_sessions: 2 };

export const acceptanceDashboard: AggregateDashboard = {
  metadata: {
    polling_fallback_endpoint: "/api/dashboard",
    live_events_endpoint: "/api/dashboard/events",
  },
  totals: {
    project_count: 3,
    enabled_project_count: 3,
    running_issue_count: 2,
    available_sessions: 4,
    max_sessions: 7,
    running_tokens: 58240,
    running_cached_tokens: 3110,
    recorded_tokens: 184320,
  },
  projects: [
    {
      project_id: "symphony",
      name: "Symphony",
      enabled: true,
      active_count: 2,
      parked_count: 1,
      terminal_count: 12,
      runner_health: "active",
      last_event: "review gate completed",
      capacity: baseCapacity,
      liveness: {
        status: "active",
        reason: "runtime polling normally",
        primary_reason_code: "active_runner_session",
        primary_reason_detail: "two runner sessions are executing",
        last_poll_at: "2026-06-19T14:12:00Z",
        last_successful_candidate_scan_at: "2026-06-19T14:10:00Z",
        capacity: baseCapacity,
      },
      cleanup_status: "clean",
      running_tokens: 43210,
      running_cached_tokens: 3110,
      recorded_tokens: 155000,
      running_issues: [
        {
          project_id: "symphony",
          project_name: "Symphony",
          issue_id: "sym-97",
          identifier: "SYM-97",
          title: "Build dashboard surfaces",
          display_status: "running",
          session_id: "oc-sym-97",
          provider_mode: "acp",
          provider_id: "runner-primary",
          process_id: 4277,
          process_alive: true,
          lifecycle_stage: "running",
          stage: "review",
          agent: "build",
          model: "gpt-5.5",
          active_agent: "typescript-engineer",
          active_model: "gpt-5.5",
          token_count: 38210,
          cached_token_count: 3110,
          subagents_used: 3,
          running_tool_count: 1,
          pending_tool_count: 2,
          todo_count: 5,
          started_at_ms: 1781880000000,
          duration_ms: 3_600_000,
          last_event: "component tests passed",
          runtime_failure_kind: null,
          acp_frame_count: 18,
          session_evidence_refs: [],
          silence_observed: false,
          worktree_path: "/workspaces/symphony/SYM-97",
        },
      ],
      self_defect_routes: [
        {
          source_issue_id: "sym-91",
          source_issue_identifier: "SYM-91",
          managed_issue_id: "sym-101",
          managed_issue_identifier: "SYM-101",
          managed_issue_url: "https://linear.app/alexey-zakharov/issue/SYM-101",
          fingerprint: "runner-timeout:sym-91",
          defect_kind: "runtime_timeout",
          severity: "high",
          relation_mode: "source_issue_blocked",
          occurrence_count: 3,
          first_seen_at: "2026-06-18T10:00:00Z",
          last_seen_at: "2026-06-19T13:55:00Z",
          next_action: "repair managed defect",
          skipped_blocker_reason: null,
          deadlock_skipped_blocker: false,
        },
      ],
    },
    {
      project_id: "nervure",
      name: "Nervure",
      enabled: true,
      active_count: 1,
      parked_count: 0,
      terminal_count: 6,
      runner_health: "idle",
      last_event: "candidate scan complete",
      capacity: { max_sessions: 2, running_sessions: 0, available_sessions: 2 },
      liveness: {
        status: "idle",
        reason: "no eligible candidates",
        primary_reason_code: "no_candidate",
        primary_reason_detail: "queue is empty after candidate scan",
        last_poll_at: "2026-06-19T14:11:00Z",
        last_successful_candidate_scan_at: "2026-06-19T14:11:00Z",
        capacity: { max_sessions: 2, running_sessions: 0, available_sessions: 2 },
      },
      cleanup_status: "clean",
      running_tokens: 0,
      running_cached_tokens: 0,
      recorded_tokens: 24000,
      running_issues: [],
      self_defect_routes: [],
    },
    {
      project_id: "atlas",
      name: "Atlas",
      enabled: true,
      active_count: 1,
      parked_count: 2,
      terminal_count: 9,
      runner_health: "blocked",
      last_event: "provider quota exhausted",
      capacity: { max_sessions: 1, running_sessions: 0, available_sessions: 1 },
      liveness: {
        status: "blocked",
        reason: "provider quota exhausted",
        primary_reason_code: "provider_blocker",
        primary_reason_detail: "waiting for quota reset",
        last_poll_at: "2026-06-19T14:09:00Z",
        last_successful_candidate_scan_at: "2026-06-19T13:58:00Z",
        capacity: { max_sessions: 1, running_sessions: 0, available_sessions: 1 },
      },
      cleanup_status: "pending",
      running_tokens: 15030,
      running_cached_tokens: 0,
      recorded_tokens: 5320,
      running_issues: [
        {
          project_id: "atlas",
          project_name: "Atlas",
          issue_id: "atl-42",
          identifier: "ATL-42",
          title: "Recover runtime poller",
          display_status: "runtime defect",
          session_id: "oc-atl-42",
          provider_mode: "omp_acp",
          provider_id: "omp-primary",
          process_id: 5321,
          process_alive: false,
          lifecycle_stage: "failed",
          stage: "failed",
          agent: "build",
          model: "gpt-5.5",
          active_agent: "failure-analyst",
          active_model: "gpt-5.5",
          token_count: 15030,
          cached_token_count: 0,
          subagents_used: 1,
          running_tool_count: 0,
          pending_tool_count: 0,
          todo_count: 2,
          duration_ms: null,
          last_event: "runtime process exited",
          runtime_failure_kind: "provider_auth_unavailable",
          acp_frame_count: 5,
          session_evidence_refs: ["sdk:auth"],
          silence_observed: true,
          worktree_path: "/workspaces/atlas/ATL-42",
        },
      ],
      self_defect_routes: [],
    },
  ],
};

const sym97Issue: IssueDetail = {
  metadata: acceptanceDashboard.metadata,
  project_id: "symphony",
  issue_id: "sym-97",
  identifier: "SYM-97",
  title: "Build dashboard surfaces",
  lifecycle_stage: "running",
  display_status: "running",
  blocker: null,
  failure: null,
  runtime_defect: null,
  self_defect_routing: null,
  git_ref: {
    branch: "sym-97-dashboard-surfaces",
    worktree_path: "/workspaces/symphony/SYM-97",
    head_sha: "abc1234",
    pr_url: "https://example.test/pr/97",
  },
  cleanup_status: "clean",
  stop_reason: null,
  last_runner_event: "component tests passed",
  runner_sessions: [
    {
      runner_session_id: "oc-sym-97",
      provider_mode: "acp",
      provider_id: "runner-primary",
      agent: "build",
      model: "gpt-5.5",
      worktree_path: "/workspaces/symphony/SYM-97",
      process_id: 4277,
      process_alive: true,
      lifecycle_stage: "running",
      current_stage: "review",
      stage_history: ["starting", "running", "review"],
      active_agent: "typescript-engineer",
      active_model: "gpt-5.5",
      subagents_used: 3,
      eval_stage: "bun test",
      message_count: 18,
      todo_count: 5,
      part_count: 64,
      token_count: 38210,
      cached_token_count: 3110,
      started_at_ms: 1781880000000,
      duration_ms: 3_600_000,
      last_event: "component tests passed",
      runtime_failure_kind: null,
      acp_frame_count: 18,
      session_evidence_refs: [],
      silence_observed: false,
      activity: {
        root_session_id: "oc-sym-97",
        running_tool_count: 1,
        pending_tool_count: 2,
        last_updated_ms: 1781883600000,
        sessions: [
          {
            session_id: "oc-sym-97",
            parent_session_id: null,
            title: "Build dashboard surfaces",
            directory: "/workspaces/symphony/SYM-97",
            agent: "build",
            model: "gpt-5.5",
            is_subagent: false,
            tokens_input: 12000,
            tokens_output: 6000,
            tokens_reasoning: 18000,
            tokens_cache_read: 2000,
            tokens_cache_write: 210,
            time_created_ms: 1781880000000,
            time_updated_ms: 1781883600000,
          },
        ],
        subagents: [
          {
            session_id: "sub-ts-1",
            parent_session_id: "oc-sym-97",
            title: "Dashboard pages",
            directory: "/workspaces/symphony/SYM-97/apps/dashboard",
            agent: "typescript-engineer",
            model: "gpt-5.5",
            is_subagent: true,
            tokens_input: 5000,
            tokens_output: 2500,
            tokens_reasoning: 6500,
            tokens_cache_read: 800,
            tokens_cache_write: 100,
            time_created_ms: 1781880900000,
            time_updated_ms: 1781883500000,
          },
        ],
        todos: [
          { session_id: "oc-sym-97", content: "Wire overview tables", status: "completed", priority: "high", position: 1, time_updated_ms: 1781881200000 },
          { session_id: "oc-sym-97", content: "Capture smoke screenshots", status: "in_progress", priority: "medium", position: 2, time_updated_ms: 1781883000000 },
          { session_id: "sub-ts-1", content: "Add inspector tabs", status: "pending", priority: "high", position: 3, time_updated_ms: 1781883300000 },
        ],
        timeline: [
          { session_id: "oc-sym-97", part_id: "p1", time_created_ms: 1781880100000, time_updated_ms: 1781880100000, kind: "message", tool: null, status: "done", title: "Scope accepted", summary: "Dashboard scope and no-display billing rule acknowledged." },
          { session_id: "sub-ts-1", part_id: "p2", time_created_ms: 1781881800000, time_updated_ms: 1781882200000, kind: "tool", tool: "bun test", status: "done", title: "Component tests", summary: "Major dashboard states rendered." },
          { session_id: "oc-sym-97", part_id: "p3", time_created_ms: 1781883000000, time_updated_ms: 1781883300000, kind: "tool", tool: "playwright", status: "running", title: "Smoke", summary: "Desktop and mobile route coverage in progress." },
        ],
      },
      activity_error: null,
    },
  ],
  eval_results: [
    { run_id: "eval-1", suite: "bun test", status: "passed", details_json: "{\"tests\":12}" },
  ],
};

const blockedIssue: IssueDetail = {
  metadata: acceptanceDashboard.metadata,
  project_id: "symphony",
  issue_id: "sym-91",
  identifier: "SYM-91",
  title: "Repair runner timeout",
  lifecycle_stage: "blocked",
  display_status: "provider/infra blocker",
  blocker: { kind: "provider_blocker", message: "provider quota exhausted", observed_at: "2026-06-19T13:55:00Z" },
  failure: null,
  runtime_defect: null,
  self_defect_routing: {
    managed_bug: {
      issue_id: "sym-101",
      identifier: "SYM-101",
      url: "https://linear.app/alexey-zakharov/issue/SYM-101",
    },
    source_context: {
      project_id: "symphony",
      issue_id: "sym-91",
      issue_identifier: "SYM-91",
      session_id: "oc-sym-97",
      process_id: null,
    },
    fingerprint: "runner-timeout:sym-91",
    severity: "high",
    defect_kind: "runtime_timeout",
    category: "runtime",
    occurrence_count: 3,
    first_seen_at: "2026-06-18T10:00:00Z",
    last_seen_at: "2026-06-19T13:55:00Z",
    relation_mode: "source_issue_blocked",
    classifier_recommendation: null,
    next_action: "repair managed defect",
    suppression_reason: null,
    skipped_blocker_reason: null,
    deadlock_skipped_blocker: false,
  },
  git_ref: null,
  cleanup_status: "pending",
  stop_reason: "owner input required",
  last_runner_event: "provider quota exhausted",
  runner_sessions: [],
  eval_results: [],
};

export const acceptanceProject: ProjectDetail = {
  metadata: acceptanceDashboard.metadata,
  project_id: "symphony",
  name: "Symphony",
  enabled: true,
  lifecycle_stage: "running",
  cleanup_status: "clean",
  capacity: baseCapacity,
  liveness: acceptanceDashboard.projects[0].liveness,
  selected_candidate: { issue_id: "sym-97", identifier: "SYM-97", lifecycle_stage: "running", reason: "capacity available" },
  suppression_reasons: [
    { issue_id: "sym-91", identifier: "SYM-91", reason_kind: "blocked", reason: "provider quota exhausted" },
  ],
  active_issues: [sym97Issue, blockedIssue],
  history_issues: [
    {
      ...sym97Issue,
      issue_id: "sym-88",
      identifier: "SYM-88",
      title: "Foundation BFF routes",
      lifecycle_stage: "completed",
      display_status: "completed",
      runner_sessions: [],
      eval_results: [{ run_id: "eval-88", suite: "bun run build", status: "passed" }],
    },
  ],
};

export const failedProject: ProjectDetail = {
  metadata: acceptanceDashboard.metadata,
  project_id: "atlas",
  name: "Atlas",
  enabled: true,
  lifecycle_stage: "running",
  cleanup_status: "pending",
  capacity: { max_sessions: 1, running_sessions: 0, available_sessions: 1 },
  liveness: acceptanceDashboard.projects[2].liveness,
  selected_candidate: null,
  suppression_reasons: [],
  active_issues: [
    {
      ...sym97Issue,
      project_id: "atlas",
      issue_id: "atl-42",
      identifier: "ATL-42",
      title: "Recover runtime poller",
      lifecycle_stage: "failed",
      display_status: "runtime defect",
      runtime_defect: {
        classification: "runtime_process_exit",
        fingerprint: "runtime-exit:atl-42",
        repair_attempt_count: 1,
        next_action: "restart supervised runner",
      },
      failure: { kind: "runtime", message: "process exited before handoff", fingerprint: "runtime-exit:atl-42", occurrence_count: 2 },
      last_runner_event: "runtime process exited",
      runner_sessions: [
        {
          ...sym97Issue.runner_sessions[0],
          runner_session_id: "oc-atl-42",
          provider_mode: "omp_acp",
          provider_id: "omp-primary",
          process_id: 5321,
          process_alive: false,
          current_stage: "failed",
          active_agent: "failure-analyst",
          token_count: 15030,
          last_event: "runtime process exited",
          runtime_failure_kind: "provider_auth_unavailable",
          acp_frame_count: 5,
          session_evidence_refs: ["sdk:auth"],
          silence_observed: true,
          activity: null,
          activity_error: "bounded activity unavailable for exited process",
        },
      ],
    },
  ],
  history_issues: [],
};

export const emptyDashboard: AggregateDashboard = {
  metadata: acceptanceDashboard.metadata,
  totals: {
    project_count: 1,
    enabled_project_count: 1,
    running_issue_count: 0,
    available_sessions: 2,
    max_sessions: 2,
    running_tokens: 0,
    running_cached_tokens: 0,
    recorded_tokens: 0,
  },
  projects: [
    {
      project_id: "symphony",
      name: "Symphony",
      enabled: true,
      active_count: 0,
      parked_count: 0,
      terminal_count: 0,
      runner_health: "idle",
      last_event: "no sessions yet",
      capacity: { max_sessions: 2, running_sessions: 0, available_sessions: 2 },
      liveness: {
        status: "idle",
        reason: "no running sessions",
        primary_reason_code: "no_candidate",
        primary_reason_detail: "waiting for eligible issues",
        last_poll_at: null,
        last_successful_candidate_scan_at: null,
        capacity: { max_sessions: 2, running_sessions: 0, available_sessions: 2 },
      },
      cleanup_status: "clean",
      running_tokens: 0,
      running_cached_tokens: 0,
      recorded_tokens: 0,
      running_issues: [],
      self_defect_routes: [],
    },
  ],
};

export const quotaNormal = {
  status: "available" as const,
  command: "provider-quota --plain",
  quota: {
    raw: {},
    buckets: [
      {
        title: "Main Codex bucket",
        windows: [
          { label: "5h", usedPercent: 24, remainingPercent: 76, resetAt: "2026-06-19T16:22:40.000Z" },
          { label: "weekly", usedPercent: 41, remainingPercent: 59, resetAt: "2026-06-24T21:18:13.000Z" },
        ],
      },
    ],
  },
};

export const quotaUnavailable = {
  status: "unavailable" as const,
  command: "provider-quota --plain",
  reason: "command_failed" as const,
  message: "quota command unavailable in this environment",
  quota: null,
};

export function projectFixture(projectId: string): ProjectDetail | undefined {
  if (projectId === "symphony") return acceptanceProject;
  if (projectId === "atlas") return failedProject;
  return undefined;
}

export function issueFixture(projectId: string, issueId: string): IssueDetail | undefined {
  const project = projectFixture(projectId);
  return project?.active_issues.concat(project.history_issues).find((issue) => issue.issue_id === issueId);
}

export function defectRoutesFromFixtures(): SelfDefectRouteSummary[] {
  return acceptanceDashboard.projects.flatMap((project) => project.self_defect_routes ?? []);
}
